version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  entry-service:
    build: ./entry-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  exit-service:
    build: ./exit-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  backend-service:
    build: ./backend-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
      - redis

  python-server:
    build: ./python-server
    ports:
      - "5000:5000"
