version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  entry-service:
    build: ./entry-service
    depends_on:
      - rabbitmq

  exit-service:
    build: ./exit-service
    depends_on:
      - rabbitmq

  backend-service:
    build: ./backend-service
    depends_on:
      - rabbitmq
      - redis

  python-server:
    build: ./python-server
    ports:
      - "5000:5000"
